// Copyright (c) 2018, 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: getting-started
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2018-06-29
:page-guide-category: basic
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to develop a Java application on Open Liberty with Maven and Docker.
:page-tags: ['Docker', 'Maven']
:page-related-guides: ['maven-intro', 'rest-intro', 'docker']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Getting started with Open Liberty
:page-seo-description: A getting started tutorial with examples on how to rapidly develop, build, and package a Java application on Open Liberty using Maven and Docker.
:guide-author: Open Liberty
= Getting started with Open Liberty

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to develop a Java application on Open Liberty with Maven and Docker.

== What you'll learn

You will learn how to run and update a simple REST microservice on an Open Liberty server.
You will use Maven throughout the guide to build and deploy the microservice as well as
to interact with the running server instance.

Open Liberty is an application server designed for the cloud. It's small, lightweight,
and designed with modern cloud-native application development in mind. It supports the
full MicroProfile and Jakarta EE APIs and is composable, meaning that you can use only the
features that you need, keeping the server lightweight, which is great for microservices.
It also deploys to every major cloud platform, including Docker, Kubernetes, and Cloud
Foundry.

Maven is an automation build tool that provides an efficient way to develop Java applications.
Using Maven, you will build a simple microservice, called `system`, that collects basic
system properties from your laptop and displays them on an endpoint that you can access
in your web browser. 

You'll also explore how to package your application
with the server runtime so that it can be deployed anywhere in one go. You will then make server configuration and code changes and see how
they are picked up by a running server.

Finally, you will package the application along with the server configuration into a Docker
image and run that image as a container.


// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" necessary in this guide


// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

Your application is configured to be built with Maven. Every Maven-configured project
contains a [hotspot]`pom.xml` file, which defines the project configuration, dependencies, plug-ins,
and so on.

Your [hotspot]`pom.xml` file is located in the `start` directory and is configured to
include the [hotspot=libertyMavenPlugin]`liberty-maven-plugin`, which allows you
to install applications into Open Liberty and manage the server instances.

pom.xml
[source, XML, linenums, role="code_column"]
----
include::finish/pom.xml[]
----

To begin, navigate to the `start` directory. Build the `system` microservice
that is provided and deploy it to Open Liberty by running the Maven
`liberty:run` goal:

[role='command']
```
cd start
mvn liberty:run
```

The `mvn` command initiates a Maven build, during which the `target` directory is created
to store all build-related files.

The `liberty:run` argument specifies the Open Liberty `run` goal, which
starts an Open Liberty server instance in the foreground.
As part of this phase, an Open Liberty server runtime is downloaded and installed into
the `target/liberty/wlp` directory, a server instance is created and configured in the
`target/liberty/wlp/usr/servers/defaultServer` directory, and the application is
installed into that server via https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_loose_applications.html[loose config^].

For more information about the Liberty Maven plug-in, see its https://github.com/WASdev/ci.maven[GitHub repository^].

When the server begins starting up, various messages display in your command-line session. Wait
for the following message, which indicates that the server startup is complete:

[source, role="no_copy"]
----
[INFO] [AUDIT] CWWKF0011I: The server defaultServer is ready to run a smarter planet.
----

To access the `system` microservice, see the http://localhost:9080/system/properties[http://localhost:9080/system/properties^] URL,
and you see a list of the various system properties of your JVM:

[source, JSON, role="no_copy"]
----
{
    "os.name": "Mac OS X",
    "java.version": "1.8.0_151",
    ...
}
----

When you need to stop the server, press `CTRL+C` in the command-line session where
you ran the server, or run the `liberty:stop` goal from the `start` directory in
another command-line session:

[role='command']
```
mvn liberty:stop
```


// =================================================================================================
// Starting and stopping the Open Liberty server in the background
// =================================================================================================

== Starting and stopping the Open Liberty server in the background

Although you can start and stop the server in the foreground by using the Maven
`liberty:run` goal, you can also start and stop the server in the background with
the Maven `liberty:start` and `liberty:stop` goals:

[role='command']
----
mvn liberty:start
mvn liberty:stop
----


// =================================================================================================
// Updating the server configuration without restarting the server
// =================================================================================================

== Updating the server configuration without restarting the server

The Open Liberty Maven plug-in includes a `dev` goal that listens for any changes in the project, 
including application source code or configuration. The Open Liberty server automatically reloads the configuration without restarting. This goal allows for quicker turnarounds and an improved developer experience.

Stop the Open Liberty server if it is running, and start it in dev mode by running the `liberty:dev` goal in the `start` directory:

[role='command']
```
mvn liberty:dev
```

Dev mode automatically picks up changes that you make to your application and allows you to run tests by pressing the `enter/return` key in the active command-line session. When you’re working on your application, rather than rerunning Maven commands, press the `enter/return` key to verify your change.

As before, you can see that the application is running by going to the http://localhost:9080/system/properties[http://localhost:9080/system/properties^] URL.

Now try updating the server configuration while the server is running in dev mode.
The `system` microservice does not currently include health monitoring to report whether the server and the microservice that it runs are healthy.
You can add health reports with the MicroProfile Health feature, which adds a `/health` endpoint to your application.
If you try to access this endpoint now at the http://localhost:9080/health/[http://localhost:9080/health/^] URL, you see a 404 error because the `/health` endpoint does not yet exist:

[source, role="no_copy"]
----
Error 404: java.io.FileNotFoundException: SRVE0190E: File not found: /health
----

To add the MicroProfile Health feature to the server, include the [hotspot=mpHealth]`mpHealth` feature in the [hotspot]`server.xml`.

[role="code_command hotspot", subs="quotes"]
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source, xml, linenums, role='code_column hide_tags=logging']
----
include::staging/server.xml[]
----

After you make the file changes, Open Liberty automatically reloads its configuration.
When enabled, the [hotspot=mpHealth]`mpHealth` feature automatically adds a `/health` endpoint to the application.
You can see the server being updated in the server log displayed in your command-line session:

[source, role="no_copy"]
----
[INFO] [AUDIT] CWWKG0016I: Starting server configuration update.
[INFO] [AUDIT] CWWKT0017I: Web application removed (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0009I: The application io.openliberty.guides.getting-started has stopped successfully.
[INFO] [AUDIT] CWWKG0017I: The server configuration was successfully updated in 0.284 seconds.
[INFO] [AUDIT] CWWKT0016I: Web application available (default_host): http://foo:9080/health/
[INFO] [AUDIT] CWWKF0012I: The server installed the following features: [mpHealth-2.2].
[INFO] [AUDIT] CWWKF0008I: Feature update completed in 0.285 seconds.
[INFO] [AUDIT] CWWKT0016I: Web application available (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0003I: The application io.openliberty.guides.getting-started updated in 0.173 seconds.
----

Try to access the `/health` endpoint again by visiting the http://localhost:9080/health[http://localhost:9080/health^] URL.
You see the following JSON:

[source, JSON, role="no_copy"]
----
{
    "checks":[],
    "status":"UP"
}
----

Now you can verify whether your server is up and running.


// =================================================================================================
// Updating the source code without restarting the server
// =================================================================================================

== Updating the source code without restarting the server

The JAX-RS application that contains your `system` microservice runs in a server from its `.class` file and other artifacts.
Open Liberty automatically monitors these artifacts, and whenever they are updated, it updates the running server without the need for the server to be restarted.

Look at your [hotspot file=0]`pom.xml` file.

pom.xml
[source, XML, linenums, role="code_column"]
----
include::finish/pom.xml[tags=**]
----

Try updating the source code while the server is running in dev mode.
At the moment, the `/health` endpoint reports whether the server is running, but the endpoint doesn't provide any details on the microservices that are running inside of the server.

MicroProfile Health offers health checks for both readiness and liveness.
A readiness check allows third-party services, such as Kubernetes, to know if the microservice is ready to process requests.
A liveness check allows third-party services to determine if the microservice is running.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `SystemReadinessCheck` class.#
`src/main/java/io/openliberty/sample/system/SystemReadinessCheck.java`
----

SystemReadinessCheck.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/sample/system/SystemReadinessCheck.java[]
----

The [hotspot=systemReadinessCheck file=1]`SystemReadinessCheck` class verifies that the 
`system` microservice is not in maintenance by checking a config property.

[role="code_command hotspot file=2", subs="quotes"]
----
#Create the `SystemLivenessCheck` class.#
`src/main/java/io/openliberty/sample/system/SystemLivenessCheck.java`
----

SystemLivenessCheck.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/sample/system/SystemLivenessCheck.java[]
----

The [hotspot=systemLivenessCheck file=2]`SystemLivenessCheck` class reports a status of 
`DOWN` if the microservice uses over 90% of the maximum amount of memory.

After you make the file changes, Open Liberty automatically reloads its configuration and the `system` application.

The following messages display in your first command-line session:

[source, role="no_copy"]
----
[INFO] [AUDIT] CWWKT0017I: Web application removed (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0009I: The application io.openliberty.guides.getting-started has stopped successfully.
[INFO] [AUDIT] CWWKT0016I: Web application available (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0003I: The application io.openliberty.guides.getting-started updated in 0.136 seconds.
----

Access the `/health` endpoint again by going to the http://localhost:9080/health[http://localhost:9080/health^] URL.
This time you see the overall status of your server and the aggregated data of the liveness and readiness checks for the `system` microservice:

[source, JSON, role="no_copy"]
----
{  
   "checks":[  
      {  
         "data":{},
         "name":"SystemResource Readiness Check",
         "status":"UP"
      },
      {  
         "data":{
            "memory used":40434888,
            "memory max":4294967296
         },
         "name":"SystemResource Liveness Check",
         "status":"UP"
      }
   ],
   "status":"UP"
}
----

You can also access the `/health/ready` endpoint by going to the http://localhost:9080/health/ready[http://localhost:9080/health/ready^] URL to view the data from the readiness health check.
Similarly, access the `/health/live` endpoint by going to the http://localhost:9080/health/live[http://localhost:9080/health/live^] URL to view the data from the liveness health check.

Making code changes and recompiling is fast and straightforward.
Open Liberty dev mode automatically picks up changes in the `.class` files and artifacts, without needing to be restarted.
Alternatively, you can run the `run` goal and manually repackage or recompile the application by using the `mvn package` command or the `mvn compile` command while the server is running. Dev mode was added to further improve the developer experience by minimizing turnaround times.


// =================================================================================================
// Checking the Open Liberty server logs
// =================================================================================================

== Checking the Open Liberty server logs

While the server is running in the foreground, it displays various console messages in
the command-line session. These messages are also logged to the `target/liberty/wlp/usr/servers/defaultServer/logs/console.log`
file. You can find the complete server logs in the `target/liberty/wlp/usr/servers/defaultServer/logs`
directory. The `console.log` and `messages.log` files are the primary log files that contain
console output of the running application and the server. More logs are created when runtime errors 
occur or whenever tracing is enabled. You can find the error logs in the
`ffdc` directory and the tracing logs in the `trace.log` file.

In addition to the log files that are generated automatically, you can enable logging of
specific Java packages or classes by using the `<logging/>` element:

[source, XML, role="no_copy"]
```
<logging traceSpecification="<component_1>=<level>:<component_2>=<level>:..."/>
```

The `component` element is a Java package or class, and the `level` element is one
of the following logging levels: `off`, `fatal`, `severe`, `warning`, `audit`, `info`,
`config`, `detail`, `fine`, `finer`, `finest`, `all`.

Try enabling detailed logging of the MicroProfile Health feature by adding the
[hotspot=logging]`<logging/>` element to your configuration file.

[role="code_command hotspot" subs="quotes"]
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source, XML, linenums, role="code_column"]
----
include::staging/server.xml[]
----

After you change the file, Open Liberty automatically reloads its configuration.

Now, when you visit the `/health` endpoint, additional traces are logged in the `trace.log` file.

[role='command']
include::{common-includes}/devmode-quit.adoc[]

// =================================================================================================
// Running the application in a Docker container
// =================================================================================================

== Running the application in a Docker container

To run the application in a container, Docker needs to be installed. For installation
instructions, see the https://docs.docker.com/install/[Official Docker Docs^].

Make sure to start your Docker daemon before you proceed.

To containerize the application, you need a `Dockerfile`. This file contains a collection
of instructions that define how a Docker image is built, what files are packaged into it,
what commands run when the image runs as a container, and other information. You can find a complete
`Dockerfile` in the `start` directory. This `Dockerfile` copies the `.war` file into a Docker
image that contains the Java runtime and a preconfigured Open Liberty server.

Run the `mvn package` command from the `start` directory so that the `.war` file resides in the `target` directory.

[role='command']
```
mvn package
```

include::{common-includes}/ol-kernel-docker-pull.adoc[]

To build and containerize the application, run the
following Docker build command in the `start` directory:

[role='command']
```
docker build -t openliberty-getting-started:1.0-SNAPSHOT .
```

The Docker `openliberty-getting-started:1.0-SNAPSHOT` image is also built from the `Dockerfile`.
To verify that the image is built, run the `docker images` command to list all local Docker images:

[role='command']
```
docker images
```

Your image should appear in the list of all Docker images:

[source, role="no_copy"]
----
REPOSITORY                     TAG             IMAGE ID        CREATED         SIZE
openliberty-getting-started    1.0-SNAPSHOT    85085141269b    21 hours ago    487MB
----

Next, run the image as a container:
[role='command']
```
docker run -d --name gettingstarted-app -p 9080:9080 openliberty-getting-started:1.0-SNAPSHOT
```

There is a bit going on here, so here's a breakdown of the command:

[cols="15, 100", options="header"]
|===
| *Flag* | *Description*
| -d     | Runs the container in the background.
| --name | Specifies a name for the container.
| -p     | Maps the container ports to the host ports.
|===

The final argument in the `docker run` command is the Docker image name.

Next, run the `docker ps` command to verify that your container started:
[role='command']
```
docker ps
```

Make sure that your container is running and does not have `Exited` as its status:

[source, role="no_copy"]
----
CONTAINER ID    IMAGE                         CREATED          STATUS           NAMES
4294a6bdf41b    openliberty-getting-started   9 seconds ago    Up 11 seconds    gettingstarted-app
----

To access the application, go to the http://localhost:9080/system/properties[http://localhost:9080/system/properties^] URL.

To stop and remove the container, run the following commands:
[role='command']
```
docker stop gettingstarted-app && docker rm gettingstarted-app
```

To remove the image, run the following command:
[role='command']
```
docker rmi openliberty-getting-started:1.0-SNAPSHOT
```

// =================================================================================================
// Developing the application in a Docker container
// =================================================================================================

== Developing the application in a Docker container

// File 0
server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

The Open Liberty Maven plug-in includes a `devc` goal that simplifies developing
your application in a Docker container by starting dev mode with container
support. This goal builds a Docker image, mounts the required directories, binds
the required ports, and then runs the application inside of a container. Dev
mode also listens for any changes in the application source code or
configuration and rebuilds the image and restarts the container as necessary.

Build and run the container by running the devc goal from the `start` directory:

// Static guide instruction
ifndef::cloud-hosted[]
[role='command']
```
mvn liberty:devc
```
endif::[]

// Cloud hosted guide instruction
ifdef::cloud-hosted[]
```
mvn liberty:devc -DserverStartTimeout=300
```
{: codeblock}
endif::[]

When you see the following message, Open Liberty is ready to run in dev mode:

[source, role="no_copy"]
----
************************************************************************
*    Liberty is running in dev mode.
----

Open another command-line session and run the `docker ps` command to verify that your container started:
[role='command']
```
docker ps
```

Your container should be running and have `Up` as its status:

[role="no_copy"]
----
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                         PORTS                                                                    NAMES
17af26af0539        guide-getting-started-dev-mode        "/opt/ol/helpers/run…"   3 minutes ago       Up 3 minutes                   0.0.0.0:7777->7777/tcp, 0.0.0.0:9080->9080/tcp, 0.0.0.0:9443->9443/tcp   liberty-dev
----

To access the application, go to the http://localhost:9080/system/properties[http://localhost:9080/system/properties^] URL. 

Dev mode automatically picks up changes that you make to your
application and allows you to run tests by pressing the `enter/return` key in the
active command-line session.

Update the [hotspot file=0]`server.xml` file to change the context root from `/` to `/dev`.

[role="code_command hotspot", subs="quotes"]
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

After you make the file changes, Open Liberty automatically reloads its
configuration. You can access the application at the
http://localhost:9080/dev/system/properties[http://localhost:9080/dev/system/properties^]
URL. Notice that context root is now `/dev`.

When you are finished, exit dev mode by pressing `CTRL+C` in the
command-line session that the container was started from, or by typing `q` and
then pressing the `enter/return` key. Either of these options stops and 
removes the container. To check that the container was stopped, run the `docker ps` command.

// =================================================================================================
// Running the application from a minimal runnable JAR
// =================================================================================================

== Running the application from a minimal runnable JAR

So far, Open Liberty was running out of the `target/liberty/wlp` directory, which
effectively contains an Open Liberty server installation and the deployed application. The
final product of the Maven build is a server package for use in a continuous integration
pipeline and, ultimately, a production deployment.

Open Liberty supports a number of different server packages. The sample application
currently generates a `usr` package that contains the servers and application to be
extracted onto an Open Liberty installation.

Instead of creating a server package, you can generate a runnable JAR file that contains
the application along with a server runtime. This JAR file can then be run anywhere and deploy
your application and server at the same time. To generate a runnable JAR file, override the 
`include` property: 
[role='command']
```
mvn liberty:package -Dinclude=runnable
```

The packaging type is overridden from the `usr` package to the `runnable`
package. This property then propagates to the [hotspot=libertyMavenPlugin file=0]`liberty-maven-plugin`
plug-in, which generates the server package based on the `openliberty-kernel` package.

When the build completes, you can find the minimal runnable `guide-getting-started.jar` file in the
`target` directory. This JAR file contains only the [hotspot=features file=1]`features` that you
explicitly enabled in your [hotspot file=1]`server.xml` file. As a result, the
generated JAR file is only about 50 MB.

To run the JAR file, first stop the server if it's running. Then, navigate to the `target`
directory and run the `java -jar` command:

[role='command']
```
java -jar guide-getting-started.jar
```

When the server starts, go to the http://localhost:9080/dev/system/properties[http://localhost:9080/dev/system/properties^] URL to access
your application that is now running out of the minimal runnable JAR file.

You can stop the server by pressing `CTRL+C` in the command-line session that the server runs in.

pom.xml
[source, XML, linenums, role="code_column"]
----
include::finish/pom.xml[]
----

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----


// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You've learned the basics of deploying and updating an application on an Open Liberty server.


include::{common-includes}/attribution.adoc[subs="attributes"]
