//  Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: getting-started
:page-layout: guide
:page-duration: 30 minutes
// :page-releasedate: 2017-09-19
:page-description: Learn how to deploy and update an application on Open Liberty using Maven and Docker.
:page-tags: ['Getting Started', 'microservices', 'Docker']
:page-related-guides: []
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
// :seo-title: Test
// :seo-description: description
= Getting started with the Open Liberty application server

Learn how to deploy and update an application on Open Liberty using Maven and Docker.

== What you'll learn

You will learn how to run a simple REST service that exposes the JVM's system properties on an Open
Liberty server using Maven.

Open Liberty is an application server designed for the cloud. It's small, lightweight, and designed
with modern cloud-native application development in mind. It supports the full MicroProfile and Java
EE APIs and is composable, so you can use just enough application server for your applications, which
is great for microservices. It also deploys to every major developer platform, including Docker,
Kubernetes, and Cloud Foundry.

Maven is an efficient way to start developing applications for Open Liberty. Using Maven, you will
create a simple microservice that collects basic system properties from your laptop and displays them
on an endpoint that you can access in your web browser.  After running this simple microservice on an
Open Liberty server, you will modify the microservice code and server configuration to experience
developing for Open Liberty.

You'll then try out the Open Liberty server command to manage and package the application with the
server, including minifying the server package so it includes only what the application needs to run
and nothing else.

Finally, you will then use the supplied Dockerfile to build a Docker image that includes the application
and server configuration and run it in Docker.


// explain what application does

// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

Before you begin, make sure to have


// =================================================================================================
// Getting Started
// =================================================================================================

//include::{common-includes}/gitclone.adoc[]

== Getting started

From command line, run the following commands to clone the repository containing a simple MicroProfile
application and then navigate into its directory:

[subs="attributes"]
----
git clone https://github.com/openliberty/guide-{projectid}.git
cd guide-{projectid}
----

The `start` directory contains a starting Java project that you will build upon, while the `finish`
directory contains the finished Java project, which is what you will build.

// There's not really any value (in this particular guide) of including the 'try it first' section.
// The start version of the application works in much the same way as the finish version. It's the
// process of looking at how the server runs the app that's important here, rather than the application
// itself. I could be convinced otherwise though?


// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

Navigate into the `start` directory and run the following command to build and run the application:

```
mvn install liberty:run-server
```

During the `install` phase, Maven creates a `target` directory where everything is built and downloaded
into. First, the application is built and its `.war` file is generated as `target/GettingStarted.war`.
Second, the Open Liberty server runtime is downloaded into `target/liberty/wlp`. Third, the Open Liberty
`defaultServer` is created under `target/liberty/wlp/usr/server` and the `src/liberty/config/server.xml`
server configuration file is copied into it. Finally, the `defaultServer` starts to run a set of integration
stops, after which it stops.

The `liberty:run-server` goal is part of the Liberty Maven plugin and it runs the `defaultServer`
in the current shell session.

For more information on the Liberty Maven plugin, visit our official https://github.com/WASdev/ci.maven[GitHub repository].

When the server starts, visit the http://localhost:9080/system/properties URL to access the application
and see the system properties of your JVM:

[source, JSON, role="no_copy"]
----
{
    "java.vendor":"Oracle Corporation",
    "default.https.port":"9443",
    "sun.java.launcher":"SUN_STANDARD",
    ...
}
----

Later, when you need to stop the server, run the `liberty:stop-server` goal like so:

```
mvn liberty:stop-server
```

// =================================================================================================
// Updating the server configuration without restarting the Open Liberty server
// =================================================================================================

== Updating the server configuration without restarting the Open Liberty server

When you're updating various server files, you can run `mvn package` command which repackages the
server while the server is still running. The `mvn package` command will work while the server is still
running as long as you don't define the `package-server` goal as an `<execution>` under the `<executions>` tag.

Let's try updating the source code while the application is running. The `system` microservice does
not currently include health monitoring to report whether the server and microservice are running.
This can be easily added with the MicroProfile Health capability.

The server should still be running but, if you've stopped it, start it again by running the
`mvn liberty:run-server` command.

Try to access the health endpoint from a browser by visiting the http://localhost:9080/health/ URL.
As expected, you should see a 404 error since the health endpoint does not yet exist:

[source, role="no_copy"]
----
Error 404: java.io.FileNotFoundException: SRVE0190E: File not found: /health
----

To add the MicroProfile Health capability to the server, add the `mpHealth-1.0` feature to the
`src/main/liberty/config/server.xml` server configuration file:

[source,xml,indent=0]
----
include::finish/src/main/liberty/config/server.xml[tag=features]
----

Next, don't close the shell where the server is running and open a new shell and repackage the server
by running the `mvn package` command. As part of the `package` phase, Maven recompiles the application
and repackages the server, although in this case, you've only updated the server configuration and not
the source code of the application.

When enabled, the `mpHealth-1.0` feature adds a `/health` endpoint to the application automatically.
This endpoint reports on the healthiness of the server instance and each microservice running in it.
You can see the server being updated in the server log thats being displayed in your first shell session:

[source, role="no_copy"]
----
[INFO] [AUDIT] CWWKG0016I: Starting server configuration update.
[INFO] [AUDIT] CWWKT0017I: Web application removed (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0009I: The application io.openliberty.guides.getting-started has stopped successfully.
[INFO] [AUDIT] CWWKG0017I: The server configuration was successfully updated in 0.284 seconds.
[INFO] [AUDIT] CWWKT0016I: Web application available (default_host): http://foo:9080/health/
[INFO] [AUDIT] CWWKF0012I: The server installed the following features: [mpHealth-1.0].
[INFO] [AUDIT] CWWKF0008I: Feature update completed in 0.285 seconds.
[INFO] [AUDIT] CWWKT0016I: Web application available (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0003I: The application io.openliberty.guides.getting-started updated in 0.173 seconds.
----

Try to access the `/health` endpoint again by visiting the http://localhost:9080/health URL. This time
you should see the following JSON:

[source, JSON, role="no_copy"]
----
{
    "checks":[],
    "outcome":"UP"
}
----


// =================================================================================================
// Updating the source code without restarting the Open Liberty server
// =================================================================================================

== Updating the source code without restarting the Open Liberty server

Your Java application is configured as a "loose application", meaning that it runs in a server from
its `.class` file and other artifacts. This eliminates the need for you to add the application `.war`
into the server's `app` directory. Open Liberty automatically monitors these artifacts and whenever
they are updated (e.g. as a result of a recompile) the server updates the running application without
needing to be restarted.

As a result, you don't need to repeatedly stop and start the server whenever you make code changes.
If your IDE is configured to recompile each time you save your changes, you don't need to even re-run
the Maven build. To recompile your code and have the running Open Liberty server pick up the new changes,
run the `mvn compile` command.

Take a look at the `pom.xml` file for the sample application. The loose application support is enabled
using the `<looseApplication>` setting under the `liberty-maven-plugin`.

The health endpoint reports that the server is running but it cannot currently provide details of the
microservice itself. To return the health status of the application, you need to add another class.

Create a new file `src/main/java/io/openliberty/sample/system/SystemHealth.java`:

[source, java]
----
include::finish/src/main/java/io/openliberty/sample/system/SystemHealth.java[tags=**;!copyright]
----

Next, run the `mvn compile` command to recompile the applicatino. You should see the following messages
appear in the server log:

[source, role="no_copy"]
----
[INFO] [AUDIT] CWWKT0017I: Web application removed (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0009I: The application io.openliberty.guides.getting-started has stopped successfully.
[INFO] [AUDIT] CWWKT0016I: Web application available (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0003I: The application io.openliberty.guides.getting-started updated in 0.136 seconds.
----

Try to access the `/health` endpoint again by visiting the http://localhost:9080/health URL. This time
you should see the overall status of your server and the microservice that it runs:


[source, JSON, role="no_copy"]
----
{
    "checks":[
        {
            "data":
            {
                "services": "available"
            },
            "name": "SystemResource",
            "state": "UP"
        }
    ],
    "outcome": "UP"
}
----


// =================================================================================================
// Checking the Open Liberty server logs
// =================================================================================================

== Checking the Open Liberty server logs

If you need to check the complete server logs, you can find them under the server's directory:
`target/liberty/wlp/usr/servers/defaultServer/logs`. This directory is created automatically when the
server first starts. There are `console.log` and `messages.log` files in the directory which contain
the console output of the running application so far. Additional logs are created in the same location
if serious errors occur. These can be found under the `ffdc` directory, which will also be created
automatically if the server encounters any errors.


// =================================================================================================
// Starting and stopping the Open Liberty server in the background
// =================================================================================================

== Starting and stopping the Open Liberty server in the background

In the previous sections, you started and stopped the server in the foreground by using the Maven
`liberty:run-server` goal. Alternatively, you can also start and stop the server in the background
using the Maven `liberty:start-server` and `liberty:stop-server` goals:

[source, role="no_copy"]
----
mvn liberty:start-server
mvn liberty:stop-server
----


// =================================================================================================
//
// =================================================================================================

== Try the minimal runnable JAR

So far, Open Liberty has been running out of the `target/liberty` directory. This directory effectively
contains an installed Liberty server and deployed application. The final product of the Maven build is
a 'server package' for use in a Continuous Integration (CI) pipeline and, ultimately, a production deployment.

Open Liberty supports a number of different server packages. The sample application currently generates a `usr` package; the package contains only the servers and the application to be exracted on to an Open Liberty installation. You can see this in the following line in the `pom.xml`:

[source,xml,indent=0]
----
include::finish/pom.xml[tag=packagingtype]
----

You can, alternatively, package the server with a full installation of Open Liberty in a runnable JAR file.

**LC: Hmm the following commands are now not working for me. The profiles are defined in the `pom.xml` and they worked last week. Wonder if there's something in conflict now using 17.0.0.4? Can't see why there would be...**

Run the following command to package your app as a runnable JAR: `mvn -P runnable-package install`

This command uses the `runnable-package` profile (defined in `pom.xml`) to temporarily override the `packaging.type` value of `usr` with `runnable` instead.

The `GettingStarted.jar` file, instead of a ZIP file, is put in the `target` directory. By default, the runnable JAR includes all the features installed with Open Liberty (the whole of Java EE 7 and MicroProfile 1.3) so the JAR file is about 97 MB. You can instead create a minimal server package that contains only the features configured in the server by running the following command: `mvn -P minify-runnable-package install`

The `server.xml` includes only the features needed by the application and so only those capabilities are included in the package (as well as any they depend on and any required for production deployment). This means the original 97 MB Open Liberty package is now about 39 MB.

**LC: Check the file sizes when minify is working.**

If the server is already running, stop it (`mvn liberty:stop-server` or CTRL + C).

Go into the `target` directory and run the runnable JAR: `java -jar GettingStarted.jar`

Access the application again: http://localhost:9080/system/properties The app is running from the minimal runnable JAR.


// =================================================================================================
//
// =================================================================================================

== Run the application in a Docker container

There is a Dockerfile in root of the project. This Dockerfile is based on the Open Liberty docker image from Docker Hub and adds in the project's server configuration and applications from an Open Liberty 'usr server package'. A usr server package contains only an application and server configuration (not a runnable server) and is designed to be unzipped over an existing Open Liberty installation.

Build a usr server package by running the original packaging command: `mvn clean package`

This creates a `target/GettingStarted.zip` containing just the `usr` directory and its contents which you can now run in Docker.

If the server is already running, stop it (`mvn liberty:stop-server` or CTRL + C).

In the `start` directory, build the Docker image from the `Dockerfile`: `docker build -t openliberty:gettingstarted .`

Run the Docker image: `docker run -p 9080:9080 -p 9443:9443 openliberty:gettingstarted`

Access the application again: http://localhost:9080/system/properties The app is running in Docker.


// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You've learnt the basics of deploying and updating an application on an Open Liberty server.

include::{common-includes}/finish.adoc[]
