//  Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: getting-started
:page-layout: guide
:page-duration: 30 minutes
// :page-releasedate: 2017-09-19
:page-description: Learn how to deploy and update an application on Open Liberty using Maven and Docker.
:page-tags: ['Getting Started', 'microservices', 'Docker']
:page-related-guides: ['docker', 'rest-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
// :seo-title: Test
// :seo-description: description
= Getting started with the Open Liberty application server

Learn how to deploy and update an application on Open Liberty using Maven and Docker.

== What you'll learn

You will learn how to run a simple REST service that exposes the JVM's system properties on an Open
Liberty server using Maven.

Open Liberty is an application server designed for the cloud. It's small, lightweight, and designed
with modern cloud-native application development in mind. It supports the full MicroProfile and Java
EE APIs and is composable, meaning that you can use only the features that you need, keeping the
server lightweight, which is great for microservices. It also deploys to every major developer platform,
including Docker, Kubernetes, and Cloud Foundry.

Maven is an automation build tool that provides an efficient way to develop applications for Open Liberty.
Using Maven, you will build a simple microservice that collects basic system properties from your
laptop and displays them on an endpoint that you can access in your web browser. You will then make
configuration and code changes and see how they are picked up by a running server. You'll also explore
how to package your the application with the server runtime so that it can be deployed anywhere in one go.

Finally, you will then containerize the application along with the server configration to run it in Docker.


// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

Before you begin, make sure that you have the following tools installed:

- `Maven` - a build automation tool. You will use Maven to build your Java application and then run
it on Open Liberty. For installation instructions see https://maven.apache.org/install.html
- `Docker` - a containerization software. You will use Docker to build an image that holds your Java
application and then run that image as a container. For installation instructions see https://docs.docker.com/install/


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// There's not really any value (in this particular guide) of including the 'try it first' section.
// The start version of the application works in much the same way as the finish version. It's the
// process of looking at how the server runs the app that's important here, rather than the application
// itself. I could be convinced otherwise though?


// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

Your application is configured to be built using Maven. Maven is a build automation tool that is
primarily used for Java projects. Every Maven-configured project contains a `pom.xml` file, which is
where the project configuration, its dependencies, and various Maven plugins are configured and defined.
To learn more about Maven, check out our https://openliberty.io/guides/maven-intro.html[Maven guide].

Your `pom.xml` file contains the Liberty Maven plugin (`liberty-maven-plugin`), which allows you to
install applications into WebSphere Liberty and Open Liberty as well as manage the server instances.

Navigate into the `start` directory and run the following command to build and run the application:

```
mvn install liberty:run-server
```

During the `install` phase, Maven creates a `target` directory where everything is built and downloaded
into. First, the application is built and its `.war` file is generated as `target/GettingStarted.war`.
Second, the Open Liberty server runtime is downloaded into `target/liberty/wlp`. Third, the Open Liberty
`defaultServer` is created under `target/liberty/wlp/usr/server` and the `src/liberty/config/server.xml`
server configuration file is copied into it. Finally, the `defaultServer` starts to run a set of integration
stops, after which it stops.

The `liberty:run-server` goal is part of the Liberty Maven plugin and it runs the `defaultServer`
in the current shell session.

For more information on the Liberty Maven plugin, visit our official https://github.com/WASdev/ci.maven[GitHub repository].

When the server starts, visit the http://localhost:9080/system/properties URL to access the application
and see the system properties of your JVM:

[source, JSON, role="no_copy"]
----
{
    "java.vendor":"Oracle Corporation",
    "default.https.port":"9443",
    "sun.java.launcher":"SUN_STANDARD",
    ...
}
----

Later, when you need to stop the server, run the `liberty:stop-server` goal like so:

```
mvn liberty:stop-server
```

// =================================================================================================
// Updating the server configuration without restarting the Open Liberty server
// =================================================================================================

== Updating the server configuration without restarting the Open Liberty server

When you're updating various server files, you can run `mvn package` command which repackages the
server while the server is still running. The `mvn package` command will work while the server is still
running as long as you don't define the `package-server` goal as an `<execution>` under the `<executions>` tag.

Let's try updating the source code while the application is running. The `system` microservice does
not currently include health monitoring to report whether the server and microservice are running.
This can be easily added with the MicroProfile Health capability.

The server should still be running but, if you've stopped it, start it again by running the
`mvn liberty:run-server` command.

Try to access the health endpoint from a browser by visiting the http://localhost:9080/health/ URL.
As expected, you should see a 404 error since the health endpoint does not yet exist:

[source, role="no_copy"]
----
Error 404: java.io.FileNotFoundException: SRVE0190E: File not found: /health
----

To add the MicroProfile Health capability to the server, add the `mpHealth-1.0` feature to the
`src/main/liberty/config/server.xml` server configuration file:

[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tag=features]
----

Next, don't close the shell where the server is running and open a new shell and repackage the server
by running the `mvn package` command. As part of the `package` phase, Maven recompiles the application
and repackages the server, although in this case, you've only updated the server configuration and not
the source code of the application.

When enabled, the `mpHealth-1.0` feature adds a `/health` endpoint to the application automatically.
This endpoint reports on the healthiness of the server instance and each microservice running in it.
You can see the server being updated in the server log thats being displayed in your first shell session:

[source, role="no_copy"]
----
[INFO] [AUDIT] CWWKG0016I: Starting server configuration update.
[INFO] [AUDIT] CWWKT0017I: Web application removed (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0009I: The application io.openliberty.guides.getting-started has stopped successfully.
[INFO] [AUDIT] CWWKG0017I: The server configuration was successfully updated in 0.284 seconds.
[INFO] [AUDIT] CWWKT0016I: Web application available (default_host): http://foo:9080/health/
[INFO] [AUDIT] CWWKF0012I: The server installed the following features: [mpHealth-1.0].
[INFO] [AUDIT] CWWKF0008I: Feature update completed in 0.285 seconds.
[INFO] [AUDIT] CWWKT0016I: Web application available (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0003I: The application io.openliberty.guides.getting-started updated in 0.173 seconds.
----

Try to access the `/health` endpoint again by visiting the http://localhost:9080/health URL. This time
you should see the following JSON:

[source, JSON, role="no_copy"]
----
{
    "checks":[],
    "outcome":"UP"
}
----


// =================================================================================================
// Updating the source code without restarting the Open Liberty server
// =================================================================================================

== Updating the source code without restarting the Open Liberty server

Your Java application is configured as a "loose application", meaning that it runs in a server from
its `.class` file and other artifacts. This eliminates the need for you to add the application `.war`
into the server's `app` directory. Open Liberty automatically monitors these artifacts and whenever
they are updated (e.g. as a result of a recompile) the server updates the running application without
needing to be restarted.

As a result, you don't need to repeatedly stop and start the server whenever you make code changes.
If your IDE is configured to recompile each time you save your changes, you don't need to even re-run
the Maven build. To recompile your code and have the running Open Liberty server pick up the new changes,
run the `mvn compile` command.

Take a look at the `pom.xml` file for the sample application. The loose application support is enabled
using the `<looseApplication>` setting under the `liberty-maven-plugin`.

The health endpoint reports that the server is running but it cannot currently provide details of the
microservice itself. To return the health status of the application, you need to add another class.

Create a new file `src/main/java/io/openliberty/sample/system/SystemHealth.java`:

[source, java]
----
include::finish/src/main/java/io/openliberty/sample/system/SystemHealth.java[tags=**;!copyright]
----

Next, run recompile the application by running the following command:

```
mvn compile
```

You should see the following messages appear in the server log:

[source, role="no_copy"]
----
[INFO] [AUDIT] CWWKT0017I: Web application removed (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0009I: The application io.openliberty.guides.getting-started has stopped successfully.
[INFO] [AUDIT] CWWKT0016I: Web application available (default_host): http://foo:9080/
[INFO] [AUDIT] CWWKZ0003I: The application io.openliberty.guides.getting-started updated in 0.136 seconds.
----

Try to access the `/health` endpoint again by visiting the http://localhost:9080/health URL. This time
you should see the overall status of your server and the microservice that it runs:


[source, JSON, role="no_copy"]
----
{
    "checks":[
        {
            "data":
            {
                "services": "available"
            },
            "name": "SystemResource",
            "state": "UP"
        }
    ],
    "outcome": "UP"
}
----


// =================================================================================================
// Checking the Open Liberty server logs
// =================================================================================================

== Checking the Open Liberty server logs

If you need to check the complete server logs, you can find them under the server's directory:
`target/liberty/wlp/usr/servers/defaultServer/logs`. This directory is created automatically when the
server first starts. There are `console.log` and `messages.log` files in the directory which contain
the console output of the running application so far. Additional logs are created in the same location
if serious errors occur. These can be found under the `ffdc` directory, which will also be created
automatically if the server encounters any errors.


// =================================================================================================
// Starting and stopping the Open Liberty server in the background
// =================================================================================================

== Starting and stopping the Open Liberty server in the background

In the previous sections, you started and stopped the server in the foreground by using the Maven
`liberty:run-server` goal. Alternatively, you can also start and stop the server in the background
using the Maven `liberty:start-server` and `liberty:stop-server` goals:

[source, role="no_copy"]
----
mvn liberty:start-server
mvn liberty:stop-server
----


// =================================================================================================
// Running the application from a minimal runnable JAR
// =================================================================================================

== Running the application from a minimal runnable JAR

So far, Open Liberty has been running out of the `target/liberty/wlp` directory. This directory effectively
contains an installed Open Liberty server and deployed application. The final product of the Maven build is
a "server package" for use in a Continuous Integration (CI) pipeline and, ultimately, a production deployment.

Open Liberty supports a number of different server packages. The sample application currently generates
a `usr` package that contains only the servers and the application to be extracted on to an Open Liberty
installation. You can see this in the following line in the `pom.xml`:

[source, xml, indent=0, role="no_copy"]
----
<include>usr</include>
----

You can, alternatively, package the server with a full installation of Open Liberty in a runnable JAR file.
To do this, run the following command:

```
mvn install -P runnable-package
```

The `-P` flag specifies a profile to be run during the build. In this case, the `runnable-package`
profile is invoked, which temporarily overrides the `packaging.type` Maven property from `usr` to
`runnable`:

[source,xml,indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=profile-runnable-package]
----

This property is then passed into the `liberty-maven-plugin` to specify what server package type
Open Liberty should generate:

[source, XML, role="no_copy"]
----
<plugin>
    <groupId>net.wasdev.wlp.maven.plugins</groupId>
    <artifactId>liberty-maven-plugin</artifactId>
    <version>2.3</version>
    <configuration>
        ...
        <packageFile>${package.file}</packageFile>
        ...
    </configuration>
</plugin>
----

After the build is finished, you can find the runnable `GettingStarted.jar` file under the `target`
directory. By default, this JAR comes with all the features available in Open Liberty (the whole of
Java EE 7 and MicroProfile 1.3), so it ends up being JAR file is about 93 MB in size. We recommend
that you omit the features that you don't need and package the JAR only with the features defined
in your `server.xml` file. To do this, run the following command:

```
mvn install -P minify-runnable-package
```

Here you are invoking the `minify-runnable-package`, which override the `package.type` property form
`usr` to `minify,runnable`. This generates a runnable JAR file that only contains the features
you've explicitly enabled in your `server.xml` file. As a result, the generated JAR is only about 39 MB.

To run the JAR, first stop the server if its running (`mvn liberty:stop-server` or CTRL + C),
then navigate to the `target` directory and run the following command:

```
java -jar GettingStarted.jar
```

Then visit the http://localhost:9080/system/properties URL to access the application that is running
from the minimal runnable JAR.


// =================================================================================================
// Running the application in a Docker container
// =================================================================================================

== Running the application in a Docker container

To containerize the application, you'll need a `Dockerfile`, which is a collection of instructions
that define how a Docker image is built, what files are packaged into it, whats executed, etc. We are
providing you with a complete `Dockerfile` under the `start` directory. This `Dockerfile` builds an
image that contains an Open Liberty runtime and the `usr` server package, which itself is made up
of the application and the server configuration.

We configured your `pom.xml` file to use the `dockerfile-maven` plugin, which automatically builds a
Docker image from a `Dockerfile` located in the same directory as the `pom.xml` file. This plugin
is defined inside the following profile:

[source, XML, role="no_copy"]
----
include::finish/pom.xml[tags=profile-docker-image]
----

To build and containerize the application, invoke the profile by running the following command

```
mvn clean package -P docker-image
```

This command generates a `usr` server package to the `target` directory and builds a `openliberty-getting-started:1.0-SNAPSHOT`
Docker image from containing this server package. Verify that this image has been built by running
the following command to list all local Docker image:

```
docker images
```

To run the image as a container, run the following command:

```
docker run -d --name gettingstarted-app -p 9080:9080 -p 9443:9443 openliberty-getting-started:1.0-SNAPSHOT
```

This command starts a `gettingstarted-app` container in the background. To access the application
running in this container, visit the http://localhost:9080/system/properties URL.

To stop and remove the container, run the following commands:

```
docker stop gettingstarted-app && docker rm gettingstarted-app
```

To remove the image, run the following command:

```
docker rmi openliberty-getting-started:1.0-SNAPSHOT
```

If you want to learn more about Docker, check out our https://openliberty.io/guides/docker.html[Docker guide].


// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You've learnt the basics of deploying and updating an application on an Open Liberty server.

include::{common-includes}/finish.adoc[]
