apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: getting-started
  namespace: dev
spec:
  applicationImage: image-registry.openshift-image-registry.svc:5000/dev/getting-started:1.0-SNAPSHOT
  pullPolicy: Always
  createKnativeService: true
  manageTLS: false
  expose: true
  service:
    type: ClusterIP
    port: 9080
